// ABOUTME: Generated C header for the helix-diff Rust library.
// ABOUTME: Provides line-level and character-level diff functions.

#ifndef HELIX_DIFF_H
#define HELIX_DIFF_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 0 = equal, 1 = delete, 2 = insert
 */
typedef struct DiffLine {
  uint8_t tag;
  char *text;
  uint32_t text_len;
} DiffLine;

typedef struct DiffHunk {
  uint32_t old_start;
  uint32_t old_count;
  uint32_t new_start;
  uint32_t new_count;
  struct DiffLine *lines;
  uint32_t line_count;
} DiffHunk;

typedef struct DiffResult {
  struct DiffHunk *hunks;
  uint32_t hunk_count;
} DiffResult;

/**
 * 0 = equal, 1 = delete, 2 = insert
 */
typedef struct InlineChunk {
  uint8_t tag;
  char *text;
  uint32_t text_len;
} InlineChunk;

typedef struct InlineResult {
  struct InlineChunk *chunks;
  uint32_t chunk_count;
} InlineResult;

struct DiffResult *helix_diff_lines(const char *old_ptr,
                                    uint32_t old_len,
                                    const char *new_ptr,
                                    uint32_t new_len,
                                    uint32_t context_lines);

struct InlineResult *helix_diff_chars(const char *old_ptr,
                                      uint32_t old_len,
                                      const char *new_ptr,
                                      uint32_t new_len);

void helix_diff_free(struct DiffResult *ptr);

void helix_inline_free(struct InlineResult *ptr);

#endif  /* HELIX_DIFF_H */
